---ordered reservoir zones. For store ORDER use REFORMS + PRODSYNC
select 
    rp.reservoir_part_code
    , TO_NUMBER(orderh.STRING_VALUE)
from reservoir_part rp
    LEFT JOIN (SELECT RESERVOIR_PART.RESERVOIR_PART_NAME
                    ,RESERVOIR_PART.RESERVOIR_PART_CODE
                    ,P_EQUIPMENT_FCL.STRING_VALUE
                FROM EQUIPMENT_INSL
                    INNER JOIN EQUIPMENT_ITEM ON EQUIPMENT_ITEM.EQUIPMENT_ITEM_S = EQUIPMENT_INSL.EQUIPMENT_ITEM_S 
                    INNER JOIN P_EQUIPMENT_FCL ON P_EQUIPMENT_FCL.OBJECT_S = EQUIPMENT_ITEM.EQUIPMENT_ITEM_S AND P_EQUIPMENT_FCL.OBJECT_T = 'EQUIPMENT_ITEM' 
                    INNER JOIN RESERVOIR_PART ON EQUIPMENT_INSL.FACILITY_S = RESERVOIR_PART.RESERVOIR_PART_S AND RESERVOIR_PART.ENTITY_TYPE_NM = 'RESERVOIR_ZONE'
                WHERE P_EQUIPMENT_FCL.BSASC_SOURCE='order no'
    ) orderh
    ON orderh.RESERVOIR_PART_CODE=rp.RESERVOIR_PART_CODE
where  rp.entity_type_nm = 'RESERVOIR_ZONE'
order by TO_NUMBER(orderh.STRING_VALUE),rp.reservoir_part_code