select distinct 
    w.WELL_ID               WELL_ID
    ,RP.RESERVOIR_PART_CODE RP_CODE
    ,RP.RESERVOIR_PART_S    RP_ID
    ,GRP.RESERVOIR_PART_CODE GRP_CODE
    ,GRP.RESERVOIR_PART_S   GRP_ID
from 
    WELL w
    ,WELLBORE wb
    ,RESERVOIR_PART rp
    ,WELLBORE_INTV wbi
    ---get WELLBORE_INTERVAL(SEC_TOPLG_OBJ)->is topological in RESERVOIR_PART(PRIM_TOPLG_OBJ) 
    LEFT JOIN TOPOLOGICAL_REL 
        ON 
            TOPOLOGICAL_REL.SEC_TOPLG_OBJ_S = wbi.WELLBORE_INTV_S
            AND 
            TOPOLOGICAL_REL.SEC_TOPLG_OBJ_T = 'WELLBORE_INTV'
            AND
            TOPOLOGICAL_REL.PRIM_TOPLG_OBJ_T='EARTH_POS_RGN'
    LEFT JOIN EARTH_POS_RGN 
        ON 
            TOPOLOGICAL_REL.PRIM_TOPLG_OBJ_S =EARTH_POS_RGN.EARTH_POS_RGN_S
            AND
            EARTH_POS_RGN.GEOLOGIC_FTR_T='RESERVOIR_PART'
    INNER JOIN RESERVOIR_PART GRP 
        ON 
            EARTH_POS_RGN.GEOLOGIC_FTR_S=GRP.RESERVOIR_PART_S
----            
where 
    wbi.WELLBORE_S=wb.WELLBORE_S
    ---get RESERVOIR_PART of WELLBORE_INTERVAL
    and wbi.GEOLOGIC_FTR_T='RESERVOIR_PART'
    and rp.RESERVOIR_PART_S=wbi.GEOLOGIC_FTR_S
    and w.WELL_S=wb.WELL_S
    {WELL_FILTER}
    {RP_FILTER}
    {GRP_FILTER}
---    and w.WELL_ID like '%040%'
    ---and rp.RESERVOIR_PART_NAME like 'PK%'